name: fh_aachen_rallye
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.6
  country_flags: ^3.0.0
  mobile_scanner: ^6.0.2
  flutter_markdown: ^0.6.2
  flutter_markdown_latex: ^0.3.4
  markdown: ^7.2.2
  vector_math: ^2.1.4
  exif: ^3.3.0
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_1.png

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-VariableFont_wght.ttf
          weight: 700
        - asset: fonts/JosefinSans-Italic-VariableFont_wght.ttf
          style: italic
    - family: Futura
      fonts:
        - asset: fonts/Futura.ttc
